# Generated by Django 5.2.1 on 2025-05-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='tipo',
            field=models.CharField(choices=[('ALL', 'Todos'), ('C', 'Comida'), ('B', 'Bebida')], default='ALL', max_length=50),
        ),
    ]
