# Generated by Django 4.2.18 on 2025-05-08 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_cardapio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='adicionado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardapio',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
