# Generated by Django 4.2.18 on 2025-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_cardapio_adicionado_cardapio_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cardapio/'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
