# Generated by Django 5.2.1 on 2025-05-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_cardapio_descricao_cardapio_foto_cardapio_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='foto',
            field=models.ImageField(blank=True, default="fotos_cardapio/default.png'", null=True, upload_to='fotos_cardapio/'),
        ),
    ]
