# Generated by Django 5.2.1 on 2025-05-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_alter_cardapio_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='promocao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Sim', max_length=50),
        ),
    ]
