# Generated by Django 5.2.1 on 2025-05-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_cardapio_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='promocao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Nao', max_length=50),
        ),
    ]
