# Generated by Django 4.2.18 on 2025-06-05 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_item', models.CharField(choices=[('PROD', 'Produto de Papelaria'), ('SERV', 'Serviço de Escritório')], default='PROD', max_length=4)),
                ('foto', models.ImageField(blank=True, default='fotos_office_items/default.png', null=True, upload_to='fotos_office_items/')),
                ('disponivel', models.BooleanField(default=True)),
                ('adicionado', models.DateTimeField(default=django.utils.timezone.now)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Op',
        ),
    ]
